# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Welcome to the Stenglein Lab
email: mark.stenglein@colostate.edu
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
description: > # this means to ignore newlines until "baseurl:"
  This is the website of the Stenglein Lab at Colorado State University
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stengleinlab.org" # the base hostname & protocol for your site
twitter_username: markstenglein
github_username:  stenglein-lab
timezone: "America/Denver"

# Build settings
markdown: kramdown

collections:
- team
